### ISSUE TITLE
DOC The parameter bibfudge is not correctly documented in the manpage

### ISSUE THREAD

**Issue by jmloyola** [debian-tex/latexmk#8] opened 2021-08-18 20:56 UTC
The parameters `-bibfudge` and `-bibfudge-` are not correctly documented in the manpage ([1](https://github.com/debian-tex/latexmk/blob/be5493ded1d2aa6dbdcf408fcb61ac68461bd274/latexmk.txt#L315), [2](https://manpages.debian.org/bullseye/latexmk/latexmk.1.en.html)).
Instead they are written down as bib**tex**fudge (note the added "tex" in the middle), giving the following output if used:
> $ latexmk -bibtexfudge -pdf  -outdir=aux -bibtex -cd src/main.tex
> Latexmk: -bibtexfudge bad option

I don't know if this is the correct place to report this issue.
Please let me know if there is a better place to do so.

Also, if in order to fix this, only the [latexmk.txt](https://github.com/debian-tex/latexmk/blob/master/latexmk.txt) needs to be modified, I can do it.
I would love to help ^^

#### Environment
OS: Debian GNU/Linux 11 (bullseye)
latexmk version: 4.70b
debian package installed: latexmk/stable 1:4.70b-0.2

**Comment by hpreusse** [comment] 2021-08-18 23:55
As this is an upstream issue, please be so kind to report @upstream. We'll try to package the latest Version asap to test if the issue is eventually solved.

**Comment by jmloyola** [comment] 2021-08-19 02:44
Thank you for the quick response :nerd_face: 

When you say to report it upstream, do you mean that I should write to the author of the package (John Collins)?
If that is the case, I don't believe it will be necessary since with version [4.72b](https://ctan.org/ctan-ann/id/mailman.1905.1618642174.4615.ctan-ann@ctan.org) of the package the issue is resolved.

If you meant to scale it with Debian, I would kindly ask you to give me some directions. Where should I raise the issue? Should I write an e-mail to the maintainer of the Debian package (Ohura Makoto)?

I think it would be nice to have a patch for this in Debian stable, but I don't really know if it is possible.

**Comment by hpreusse** [comment] 2021-09-03 20:38
New version [is packaged here](https://freeshell.de/hille42/latexmk_6/), let me know if it solves the issue.

**Comment by jmloyola** [comment] 2021-09-04 02:27
I think all the newer versions have the documentation typo fixed, so this will do I guess.

I opened the issue thinking this was the place to report it so it get fixed in Debian stable. If this is not the correct place, please feel free to close the issue.

**Comment by hpreusse** [comment] 2021-09-04 06:37
We in Debian prefer our own bug tracker: https://bugs.debian.org/ . Github is just the choice to hist the development data.

Anyway: thanks to hear that the issue has been solved. Closing it.

**Closed by hpreusse** 2021-09-04 06:37 UTC
